# Generated by Django 3.2 on 2024-02-29 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_test_end_date_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 11, 47, 47, 767969, tzinfo=utc), verbose_name='tugash sanasi'),
        ),
    ]
