# Generated by Django 3.2 on 2024-02-29 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 11, 49, 43, 685764, tzinfo=utc), verbose_name='tugash sanasi'),
        ),
    ]
